"""add rating

Revision ID: 777bb124d9d3
Revises: af3efccc3a62
Create Date: 2024-02-19 19:21:12.248490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777bb124d9d3'
down_revision = 'af3efccc3a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
